spring.application.name=blog

# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}


# spring.jpa.hibernate.ddl-auto=update

# server.port=${PORT:8080}
# spring.jpa.properties.hibernate.format_sql=true

# Database URL
spring.datasource.url=jdbc:postgresql://localhost:5432/blog

# Database credentials
spring.datasource.username=postgres
spring.datasource.password=2004

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings (optional but recommended)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect